name: integration-tests-only

on: workflow_dispatch  # Manual trigger

jobs:
  integration-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Latest Typesense Binary
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tests.yml
          name: typesense-server
          path: ./typesense-server-binary
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_conclusion: success
          search_artifacts: true
          skip_unpack: false

      - name: Make binary executable
        run: chmod +x ./typesense-server-binary/typesense-server

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and Run Tests
        working-directory: benchmark
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
          ./dist/index.js test \
            --binary $(pwd)/../typesense-server-binary/typesense-server \
            --working-directory $(pwd)/../tmp/test -y -v
